##1. Giới thiệu bài tập
Mục tiêu của bài tập là tìm điểm tối ưu (minimum) của hàm số $f(w_1, w_2) = 0.1w_1^2 + 2w_2^2$ sử dụng thuật toán Gradient Descent + Momentum.

##2. Thực hiện tính toán
###2.1 Epoch 1
- **STEP1**: Tính gradient $dW$:

$\frac{\partial f}{\partial w_1} = 0.2w_1, \quad \frac{\partial f}{\partial w_2} = 4w_2$

- **STEP2**: Tính giá trị $V_{1, t}$ và $V_{2, t}$:

$V_{1, t} = βV_{1, t-1} + (1 - β)0.2w_1$

$V_{2, t} = βV_{2, t-1} + (1 - β)4w_1$

- **STEP3**: Cập nhật $w_1$ và $w_2$:

$w_1 = w_1 - α ⋅ V_{1, t}$

$w_2 = w_2 - α ⋅ V_{2, t}$

###2.2 Epoch 2
- Thực hiện tính toán đối với $w_1$ và $w_2$ tương tự các bước **STEP1**, **STEP2** và **STEP3** như epoch 1.

In [ ]:
import numpy as np

In [ ]:
def df_w(W):
  dw_1 = 0.2 * W[0]
  dw_2 = 4 * W[1]
  dW = np.array([dw_1, dw_2])
  return dW

In [ ]:
def sgd_momentum(W, dW, lr, V, beta):
  V = beta * V + (1 - beta) * dW
  W = W - lr * V
  return W, V

In [ ]:
def train_p1(sgd_momentum, lr, epochs):
  W = np.array([-5, -2], dtype=np.float32)
  V = np.array([0, 0], dtype=np.float32)
  results = [W]
  for epoch in range(epochs):
    dW = df_w(W)
    W, V = sgd_momentum(W, dW, lr, V, 0.5)
    results.append(W)
  return results

In [ ]:
results = train_p1(sgd_momentum, 0.6, 30)

In [ ]:
results

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 