## 1. Giới thiệu bài tập
Mục tiêu bài tập là tìm điểm tối ưu (minimum) của hàm số: $f(w_1, w_2) = 0.1w_1^2 + 2w_2^2$ sử dụng thuật toán Gradient Descent với 2 epoch.

## 2. Thực hiện bài toán

### 2.1. Epoch 1
- **STEP 1**: Tính gradient $dW$:

$\frac{\partial f}{\partial w_1} = 0.2w_1, \quad \frac{\partial f}{\partial w_2} = 4w_2$

- **STEP 2**: Cập nhật $w_1$ và $w_2$:

$w_1 = w_1 - α ⋅ 0.2w_1$

$w_2 = w_2 - α \cdot 4w_2$

### 2.2. Epoch 2
- **STEP 1**: Sử dụng giá trị $w_1$ và $w_2$ đã cập nhật từ Epoch 1, tiếp tục tính gradient $dW$.
- **STEP 2**: Tiếp tục cập nhập $w_1$ và $w_2$ theo công thức thuật toán Gradient Descent.

## 3. Kết quả
- Giá trị $(w_1, w_2)$ sau từng epoch.
- Giá trị hàm số $f(w_1, w_2)$ sau từng epoch.


In [ ]:
import numpy as np

In [ ]:
def df_w(W):
  dw_1 = 0.2 * W[0]
  dw_2 = 4 * W[1]
  dW = np.array([dw_1, dw_2])
  return dW

In [ ]:
def SGD(W, dW, lr):
  W = W - lr * dW
  return W

In [ ]:
def train_p1(SGD, lr, epochs):
  W = np.array([-5, -2], dtype=np.float32)
  results = [W]

  for epoch in range(epochs):
    dW = df_w(W)
    W = SGD(W, dW, lr)
    results.append(W)

  return results

In [ ]:
results = train_p1(SGD, 0.4, 30)
results

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-