##1. Giới thiệu bài tập
Mục tiêu của bài tập là tìm điểm tối ưu (minimum) của hàm số $f(w_1, w_2) = 0.1w_1^2 + 2w_2^2$ sử dụng thuật toán RMSProp.

##2. Thực hiện tính toán
###2.1 Epoch 1
- **STEP1**: Tính gradient $dW$:

$\frac{\partial f}{\partial w_1} = 0.2w_1, \quad \frac{\partial f}{\partial w_2} = 4w_2$

- **STEP2**: Tính giá trị $S_{1, t}$ và $S_{2, t}$:

$S_{1,t} = γS_{1,t-1} + (1 - γ)(0.2w_1)^2$

$S_{2, t} = γS_{2, t-1} + (1 - γ)(4w_2)^2$

- **STEP3**: Cập nhật $w_1$ và $w_2$:

$w_1 = w_1 - \alpha \cdot \frac{0.2w_1}{\sqrt{S_{1, t} + ϵ}}$

$w_2 = w_2 - \alpha \cdot \frac{4w_2}{\sqrt{S_{2, t} + \epsilon}}$

###2.2 Epoch 2
- Thực hiện tính toán đối với $w_1$ và $w_2$ tương tự các bước **STEP1**, **STEP2** và **STEP3** như epoch 1.

In [ ]:
import numpy as np

In [ ]:
def df_w(W):
  dw_1 = 0.2 * W[0]
  dw_2 = 4 * W[1]
  dW = np.array([dw_1, dw_2])
  return dW

In [ ]:
def RMSProp(W, dW, lr, S, gamma):
  epsilon = 1e-6
  S = gamma * S + (1 - gamma) * dW ** 2
  W = W - lr * dW / np.sqrt(S + epsilon)
  return W, S

In [ ]:
def train_p1(RMSProp, lr, epochs):
  W = np.array([-5, -2], dtype=np.float32)
  S = np.array([0, 0], dtype=np.float32)
  results = [W]
  for epoch in range(epochs):
    dW = df_w(W)
    W, S = RMSProp(W, dW, lr, S, 0.9)
    results.append(W)
  return results

In [ ]:
results = train_p1(RMSProp, 0.3, 30)
results

[array([-5., -2.], dtype=float32),
 array([-4.05132145, -1.05131678]),
 array([-3.43519754, -0.59152343]),
 array([-2.95893693, -0.3294394 ]),
 array([-2.56546289, -0.17756482]),
 array([-2.22920552, -0.09163256]),
 array([-1.93626752, -0.04494499]),
 array([-1.67817686, -0.02081423]),
 array([-1.44934985, -0.00903559]),
 array([-1.24588199, -0.00364591]),
 array([-1.06490301, -0.00135351]),
 array([-9.04202260e-01, -4.56444431e-04]),
 array([-7.61996495e-01, -1.37562928e-04]),
 array([-6.36778499e-01, -3.62601019e-05]),
 array([-5.27215237e-01, -8.11337456e-06]),
 array([-4.32078505e-01, -1.47473412e-06]),
 array([-3.50198507e-01, -2.02783991e-07]),
 array([-2.80434649e-01, -1.84231187e-08]),
 array([-2.21659834e-01, -7.67742748e-10]),
 array([-1.72755512e-01,  7.80451998e-12]),
 array([-1.32615134e-01, -5.05794800e-13]),
 array([-1.00153779e-01,  6.19123501e-14]),
 array([-7.43217708e-02, -1.13373781e-14]),
 array([-5.41201278e-02,  2.80166702e-15]),
 array([-3.86159157e-02, -8.81341